MODULE XInput_DLM
DESCRIPTION	"Windows XInput support for IDL"
VERSION 1.0
SOURCE Richie Zeng - rfzeng@lbl.gov
BUILD_DATE July 25, 2011
FUNCTION JOYGETBUTTONS 1 1
FUNCTION JOYGETONEBUTTON 2 2
FUNCTION JOYGETDPAD 1 1
FUNCTION JOYGETLXY 1 1
FUNCTION JOYGETRXY 1 1
FUNCTION JOYGETTRIGGER 1 1
FUNCTION JOYISCONNECTED 1 1
FUNCTION JOYVIBRATELOW 2 2
FUNCTION JOYVIBRATEHIGH 2 2
FUNCTION JOYVIBRATE 2 2
PROCEDURE JOYUPDATE 1 1
